/*
 */
package com.uncuyo.pixelArena.view;

import com.uncuyo.pixelArena.control.EmpresaControlador;

/**
 *
 * @author joaqu
 */
public class IngresarEmpresaFrame extends javax.swing.JFrame {

   private EmpresaControlador empresaControlador;
    
    public IngresarEmpresaFrame() {
        initComponents();
        empresaControlador = new EmpresaControlador();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoNombre = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoEmail = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        textoAviso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoNumTelefono = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar una nueva empresa");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar Empresa");

        jLabel2.setText("Nombre");

        textoNombre.setText("Ingrese el nombre");
        textoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoNombreMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(textoNombre);

        jLabel3.setText("Email");

        textoEmail.setText("Ingrese el mail de la empresa");
        textoEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoEmailMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(textoEmail);

        jToggleButton1.setText("Aceptar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarClicked(evt);
            }
        });

        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarClicked(evt);
            }
        });

        jLabel4.setText("Número de teléfono");

        textoNumTelefono.setText("Ingrese el número de teléfono");
        textoNumTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoNumTelefonoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoNumTelefonoMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(textoNumTelefono);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(textoAviso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton2)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane3))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addGap(36, 36, 36)
                .addComponent(textoAviso)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        textoAviso.getAccessibleContext().setAccessibleName("textoAviso");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNombreMouseEntered
        if(textoNombre.getText().equals("Ingrese el nombre")){
            textoNombre.setText("");
        }
        
    }//GEN-LAST:event_textoNombreMouseEntered

    private void textoNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNombreMouseExited
        if(textoNombre.getText().equals("")){
            textoNombre.setText("Ingrese el nombre");
        }
        
    }//GEN-LAST:event_textoNombreMouseExited

    private void textoEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoEmailMouseEntered
        if(textoEmail.getText().equals("Ingrese el mail de la empresa")){
            textoEmail.setText("");
        }
    }//GEN-LAST:event_textoEmailMouseEntered

    private void textoEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoEmailMouseExited
        if(textoEmail.getText().equals("")){
            textoEmail.setText("Ingrese el mail de la empresa");
        }
    }//GEN-LAST:event_textoEmailMouseExited

    private void cancelarClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarClicked
        this.dispose();
    }//GEN-LAST:event_cancelarClicked

    private void aceptarClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarClicked
        textoAviso.setText(empresaControlador.crearEmpresa(textoNombre.getText(), textoEmail.getText(), textoNumTelefono.getText()));
        
    }//GEN-LAST:event_aceptarClicked

    private void textoNumTelefonoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNumTelefonoMouseEntered
        if(textoNumTelefono.getText().equals("Ingrese el número de teléfono")){
            textoNumTelefono.setText("");
        }
    }//GEN-LAST:event_textoNumTelefonoMouseEntered

    private void textoNumTelefonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNumTelefonoMouseExited
        if(textoNumTelefono.getText().equals("")){
            textoNumTelefono.setText("Ingrese el número de teléfono");
        }
    }//GEN-LAST:event_textoNumTelefonoMouseExited


    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarEmpresaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel textoAviso;
    private javax.swing.JTextPane textoEmail;
    private javax.swing.JTextPane textoNombre;
    private javax.swing.JTextPane textoNumTelefono;
    // End of variables declaration//GEN-END:variables
}
