package com.uncuyo.pixelArena.view;

import com.uncuyo.pixelArena.control.JuegoControlador;
import com.uncuyo.pixelArena.control.TorneoControlador;
import com.uncuyo.pixelArena.model.Juego;
import java.util.List;

public class IngresarTorneoFrame extends javax.swing.JFrame {

    private JuegoControlador juegoControlador;
    private TorneoControlador torneoControlador;
    private MainFrame mainFrame;

    public IngresarTorneoFrame() {
        initComponents();
        juegoControlador = new JuegoControlador();
        torneoControlador = new TorneoControlador();
        List<Juego> juegos = juegoControlador.listarJuegos();
        for (Juego juego : juegos) {
            if (juego.isActivo()) {
                juegosBox.addItem(juego.getNombre());
            }
        }
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoNombre = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDescripcion = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        textoAviso = new javax.swing.JLabel();
        juegosBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        fechaInicio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaFinal = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoCosto = new javax.swing.JTextPane();
        textoAviso2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar nuevo torneo");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar Torneo");

        jLabel2.setText("Nombre");

        textoNombre.setText("Ingrese el nombre");
        textoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoNombreMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(textoNombre);

        jLabel3.setText("Descripción");

        textoDescripcion.setText("Ingrese una descripción");
        textoDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoDescripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoDescripcionMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(textoDescripcion);

        jToggleButton1.setText("Aceptar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarClicked(evt);
            }
        });

        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarClicked(evt);
            }
        });

        jLabel4.setText("Juego");

        fechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/mm/yyyy"))));
        fechaInicio.setText("dd/mm/aaaa");
        fechaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechaInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechaInicioMouseExited(evt);
            }
        });

        jLabel5.setText("Fecha inicio");

        jLabel6.setText("Fecha final");

        fechaFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/mm/yyyy"))));
        fechaFinal.setText("dd/mm/aaaa");
        fechaFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechaFinalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechaFinalMouseExited(evt);
            }
        });

        jLabel7.setText("Costo inscripción");

        textoCosto.setText("Ingrese el precio de inscripción");
        textoCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoCostoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoCostoMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(textoCosto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(textoAviso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaInicio)
                    .addComponent(juegosBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(fechaFinal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(textoAviso2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juegosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(textoAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoAviso2)
                .addGap(19, 19, 19))
        );

        textoAviso.getAccessibleContext().setAccessibleName("textoAviso");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNombreMouseEntered
        if (textoNombre.getText().equals("Ingrese el nombre")) {
            textoNombre.setText("");
        }

    }//GEN-LAST:event_textoNombreMouseEntered

    private void textoNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoNombreMouseExited
        if (textoNombre.getText().equals("")) {
            textoNombre.setText("Ingrese el nombre");
        }

    }//GEN-LAST:event_textoNombreMouseExited

    private void textoDescripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDescripcionMouseEntered
        if (textoDescripcion.getText().equals("Ingrese una descripción")) {
            textoDescripcion.setText("");
        }
    }//GEN-LAST:event_textoDescripcionMouseEntered

    private void textoDescripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoDescripcionMouseExited
        if (textoDescripcion.getText().equals("")) {
            textoDescripcion.setText("Ingrese una descripción");
        }
    }//GEN-LAST:event_textoDescripcionMouseExited

    private void cancelarClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarClicked
        this.dispose();
    }//GEN-LAST:event_cancelarClicked

    private void aceptarClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarClicked
        textoAviso2.setText(torneoControlador.crearTorneo(textoNombre.getText(), 
                textoDescripcion.getText(), (String) juegosBox.getSelectedItem(), 
                fechaInicio.getText(), fechaFinal.getText(), textoCosto.getText()));
        mainFrame = new MainFrame();
        mainFrame.llenarTablas();


    }//GEN-LAST:event_aceptarClicked

    private void textoCostoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCostoMouseEntered
        if (textoCosto.getText().equals("Ingrese el precio de inscripción")) {
            textoCosto.setText("");
        }
    }//GEN-LAST:event_textoCostoMouseEntered

    private void textoCostoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoCostoMouseExited
        if (textoCosto.getText().equals("")) {
            textoCosto.setText("Ingrese el precio de inscripción");
        }
    }//GEN-LAST:event_textoCostoMouseExited

    private void fechaInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaInicioMouseEntered
        if (fechaInicio.getText().equals("dd/mm/aaaa")) {
            fechaInicio.setText("");
        }
    }//GEN-LAST:event_fechaInicioMouseEntered

    private void fechaInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaInicioMouseExited
        if (fechaInicio.getText().equals("")) {
            fechaInicio.setText("dd/mm/aaaa");
        }
    }//GEN-LAST:event_fechaInicioMouseExited

    private void fechaFinalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaFinalMouseEntered
        if (fechaFinal.getText().equals("dd/mm/aaaa")) {
            fechaFinal.setText("");
        }
    }//GEN-LAST:event_fechaFinalMouseEntered

    private void fechaFinalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaFinalMouseExited
        if (fechaFinal.getText().equals("")) {
            fechaFinal.setText("dd/mm/aaaa");
        }
    }//GEN-LAST:event_fechaFinalMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarTorneoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarTorneoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarTorneoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarTorneoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarTorneoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField fechaFinal;
    private javax.swing.JFormattedTextField fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JComboBox<String> juegosBox;
    private javax.swing.JLabel textoAviso;
    private javax.swing.JLabel textoAviso2;
    private javax.swing.JTextPane textoCosto;
    private javax.swing.JTextPane textoDescripcion;
    private javax.swing.JTextPane textoNombre;
    // End of variables declaration//GEN-END:variables
}
